buildscript {
    repositories {
        maven { url 'https://maven.aliyun.com/repository/central' }
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/jcenter' }
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
        maven { url 'https://maven.aliyun.com/repository/grails-core' }
        maven { url 'https://gitee.com/liuchaoya/libcommon/raw/master/repository/' }
        // 华为开源镜像：https://mirrors.huaweicloud.com/
        maven { url 'https://repo.huaweicloud.com/repository/maven/' }
        // JitPack 远程仓库：https://jitpack.io
        maven { url 'https://jitpack.io' }
        mavenCentral()
        google()
        // noinspection JcenterRepositoryObsolete
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.6.1'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.25'
    }
}

allprojects {
//    repositories {
//        maven { url 'https://maven.aliyun.com/repository/public' }
//        maven { url 'https://maven.aliyun.com/repository/google' }
//        maven { url 'https://repo.huaweicloud.com/repository/maven/' }
//        maven { url 'https://jitpack.io' }
//        mavenCentral()
//        google()
//        // noinspection JcenterRepositoryObsolete
//        jcenter()
//    }

    // 读取 local.properties 文件配置
    def properties = new Properties()
    def localPropertiesFile = rootProject.file("local.properties")
    if (localPropertiesFile.exists()) {
        localPropertiesFile.withInputStream { inputStream ->
            properties.load(inputStream)
        }
    }

    String buildDirPath = properties.getProperty("build.dir")
    if (buildDirPath != null && buildDirPath != "") {
        // 将构建文件统一输出到指定的目录下
        setBuildDir(new File(buildDirPath, rootProject.name + "/build/${path.replaceAll(':', '/')}"))
    } else {
        // 将构建文件统一输出到项目根目录下的 build 文件夹
        setBuildDir(new File(rootDir, "build/${path.replaceAll(':', '/')}"))
    }
}

tasks.register('clean', Delete) {
    delete rootProject.buildDir
}

subprojects {
    apply plugin: 'maven-publish'
    def versionToPublished = '0.0.4'
    def groupIdToPublished = 'com.github.mozhimen.APermissionKit_XXPermissions'

    afterEvaluate { project ->

        if (project.plugins.hasPlugin('java-library')|| project.plugins.hasPlugin('java')) {
            publishing {
                publications {
                    create("mavenJava", MavenPublication) {
                        from components.java
                        groupId = 'com.github.mozhimen'
                        artifactId = project.name
                        version = versionToPublished

                        pom.withXml {
                            def root = asNode()
                            def dependenciesNode = root.dependencies ? root.dependencies[0] : root.appendNode('dependencies')

                            // 在执行时获取依赖，而不是配置时
                            def apiDeps = project.configurations.api.allDependencies.toList()
                            def implDeps = project.configurations.implementation.allDependencies.toList()

                            apiDeps.each { dep ->
                                def depNode = dependenciesNode.appendNode("dependency")
                                def groupId //= dep instanceof ProjectDependency ? project.rootProject.group.toString() : dep.group
                                def version
                                if(dep instanceof ProjectDependency){
                                    groupId = groupIdToPublished
                                    version = versionToPublished
                                }else{
                                    groupId = dep.group
                                    version = dep.version
                                }
                                depNode.appendNode("groupId",groupId)
                                depNode.appendNode("artifactId", dep.name)
                                depNode.appendNode("version",version)
                                depNode.appendNode("scope", "compile")

                                println "[POM DEBUG] runtime dependency -> groupId: $groupId, artifactId: ${dep.name}, version: $version"
                            }

                            implDeps.each { dep ->
                                def depNode = dependenciesNode.appendNode("dependency")
                                def groupId //= dep instanceof ProjectDependency ? project.rootProject.group.toString() : dep.group
                                def version
                                if(dep instanceof ProjectDependency){
                                    groupId = groupIdToPublished
                                    version = versionToPublished
                                }else{
                                    groupId = dep.group
                                    version = dep.version
                                }
                                depNode.appendNode("groupId",groupId)
                                depNode.appendNode("artifactId", dep.name)
                                depNode.appendNode("version",version)
                                depNode.appendNode("scope", "compile")

                                println "[POM DEBUG] runtime dependency -> groupId: $groupId, artifactId: ${dep.name}, version: $version"
                            }
                        }
                    }
                }
            }
        }

        else if (project.plugins.hasPlugin('com.android.library')) {
            project.android.libraryVariants.all { variant ->
                if (variant.buildType.name == "release") {
                    def releaseAar = project.tasks.named("bundle${variant.name.capitalize()}Aar")

                    publishing {
                        publications {
                            create("release", MavenPublication) {
                                groupId = 'com.github.mozhimen'
                                artifactId = project.name
                                version = versionToPublished

                                artifact(releaseAar) {
                                    builtBy releaseAar
                                }

                                pom.withXml {
                                    def root = asNode()
                                    def dependenciesNode = root.dependencies ? root.dependencies[0] : root.appendNode('dependencies')

                                    // 在执行时获取依赖
                                    def apiDeps = project.configurations.api.allDependencies.toList()
                                    def implDeps = project.configurations.implementation.allDependencies.toList()

                                    apiDeps.each { dep ->
                                        def depNode = dependenciesNode.appendNode("dependency")
                                        def groupId //= dep instanceof ProjectDependency ? project.rootProject.group.toString() : dep.group
                                        def version
                                        if(dep instanceof ProjectDependency){
                                            groupId = groupIdToPublished
                                            version = versionToPublished
                                        }else{
                                            groupId = dep.group
                                            version = dep.version
                                        }
                                        depNode.appendNode("groupId",groupId)
                                        depNode.appendNode("artifactId", dep.name)
                                        depNode.appendNode("version",version)
                                        depNode.appendNode("scope", "compile")

                                        println "[POM DEBUG] runtime dependency -> groupId: $groupId, artifactId: ${dep.name}, version: $version"
                                    }

                                    implDeps.each { dep ->
                                        def depNode = dependenciesNode.appendNode("dependency")
                                        def groupId //= dep instanceof ProjectDependency ? project.rootProject.group.toString() : dep.group
                                        def version
                                        if(dep instanceof ProjectDependency){
                                            groupId = groupIdToPublished
                                            version = versionToPublished
                                        }else{
                                            groupId = dep.group
                                            version = dep.version
                                        }
                                        depNode.appendNode("groupId",groupId)
                                        depNode.appendNode("artifactId", dep.name)
                                        depNode.appendNode("version",version)
                                        depNode.appendNode("scope", "compile")

                                        println "[POM DEBUG] runtime dependency -> groupId: $groupId, artifactId: ${dep.name}, version: $version"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
